# https://docs.github.com/en/actions
# https://github.com/github/super-linter
name: Super-Linter

on: [pull_request]

jobs:
  superlinter:
    name: Run GitHub Super-Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: github/super-linter@v4.7.2
        env:
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_SHELL_SHFMT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
